steps:
  - name: 'golang:1.13-stretch'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/kaniko-project/executor:v0.10.0'
    args:
      - --destination=gcr.io/$PROJECT_ID/gcpug/nouhau2web/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h